name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        deactivate

  test:
    runs-on: ubuntu-latest
    needs: build  # This will run after the build job completes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        deactivate

    - name: Run Tests
      run: |
        source venv/bin/activate
        python manage.py test price_aggregator  # Adjust to your app's name if necessary
        deactivate

  release:
    runs-on: ubuntu-latest
    needs: build  # This will run after the build job completes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
        docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: release  # This will run after the release job completes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH and deploy
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 400 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }} &&
          docker run -d -p 5000:8000 ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}"

